project:
  type: website
  output-dir: docs
  resources:
    - "files/"

execute:
  freeze: auto

bibliography: files/bib/references.bib
csl: files/bib/apa7.csl

website:
  title: "IMSB2026"
  description: "Introduction à la modélisation statistique bayésienne"
  favicon: "files/cover.png"
  
  page-navigation: true
  
  navbar:
    pinned: true
    search: true
    background: "#1c5253"
    right:
      - syllabus.qmd
      - planning.qmd
      - content/index.qmd
      - resources.qmd
      - install.qmd
        
  sidebar:
    - title: "Planning"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Vue d'ensemble"
          contents:
            - content/index.qmd
        - section: "Planning détaillé"
          contents:
            - text: "Introduction à l'inférence bayésienne"
              file: content/cours01.qmd
            - text: "Modèle Beta-Binomial"
              file: content/cours02.qmd
            - text: "Modèle de régression linéaire, intro brms"
              file: content/cours03.qmd
            - text: "Modèle de régression linéaire (suite)"
              file: content/cours04.qmd
            - text: "Markov Chain Monte Carlo"
              file: content/cours05.qmd
            - text: "Modèle linéaire généralisé"
              file: content/cours06.qmd
            - text: "Comparaison de modèles"
              file: content/cours07.qmd
            - text: "Modèles multi-niveaux (généralisés)"
              file: content/cours08.qmd
              
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} 2026 by [Ladislas Nalborczyk](https://www.barelysignificant.com).<br>
      Adapted from [this course](https://evalf22.classes.andrewheiss.com) by [Andrew Heiss](https://www.andrewheiss.com).
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/lnalborczyk/IMSB2026)

format:
  html:
    theme:
      - minty
      - custom.scss
    code-bg: blue
    toc: true
    highlight-style: zenburn
